let pokemonRepository=function(){let e=[];function t(t){"object"==typeof t&&"name"in t&&"detailsUrl"in t?e.push(t):console.error("Invalid Pok\xe9mon data")}function o(){return e}async function n(e){let t=e.detailsUrl;try{let o=await fetch(t),n=await o.json();e.imageUrl=n.sprites.front_default,e.height=n.height,e.types=n.types.map(e=>e.type.name)}catch(i){console.error(i)}}function i(e){n(e).then(()=>{var t;let o,n,i;t=e,o=document.querySelector("#pokemonModalLabel"),document.querySelector(".modal-body"),n=document.querySelector("#pokemonImage"),i=document.querySelector("#pokemonHeight"),o.innerText=t.name,n.setAttribute("src",t.imageUrl),n.setAttribute("alt",`${t.name} image`),i.innerText=`Height: ${t.height}`,$("#pokemonModal").modal("show")})}return{add:t,getAll:o,addListItem:function e(t){let o=document.querySelector(".pokemon-list"),n=document.createElement("li"),r=document.createElement("button");n.classList.add("list-group-item"),r.innerText=t.name,r.classList.add("btn","btn-primary"),r.addEventListener("click",function(){i(t)}),n.appendChild(r),o.appendChild(n)},loadList:function e(){return fetch("https://pokeapi.co/api/v2/pokemon/?limit=150").then(e=>e.json()).then(e=>{e.results.forEach(e=>{t({name:e.name,detailsUrl:e.url})})}).catch(e=>{console.error(e)})},showDetails:i}}();pokemonRepository.loadList().then(()=>{pokemonRepository.getAll().forEach(e=>{pokemonRepository.addListItem(e)})});































